"""Human-reviewable calibration audit (Milestone 3.1 §9).

Generated from the configuration itself, so it can never drift from what
the engine uses:  python -m ascend_engine audit > docs/CALIBRATION_AUDIT_v0.1.md
"""

from __future__ import annotations

from .config import ATTRIBUTES, EngineConfig, load_config
from .scoring.curves import Curve

LEVELS = ("very low", "low", "mid", "high", "very high")
EXAMPLE_BODY_MASSES = (60.0, 80.0, 100.0)


def _fmt(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def _usage(curve_id: str, cfg: EngineConfig) -> list[str]:
    rows = []
    for attribute in ATTRIBUTES:
        for sd in cfg.attributes[attribute]:
            for source in sd.sources:
                if source.curve == curve_id:
                    share = source.weight / sum(s.weight for s in sd.sources)
                    kind = " (alternative sources)" if sd.alternatives else ""
                    rows.append(
                        f"{attribute} → {sd.name}: subdomain weight {_fmt(sd.weight)}, "
                        f"source share {_fmt(share)}{kind}"
                    )
    return rows


def _levels(curve: Curve) -> list[tuple[str, float]]:
    """Raw values at 0 / 25 / 50 / 75 / 100 % of the calibrated range, worst to best."""
    low, high = curve.points[0][0], curve.points[-1][0]
    fractions = (0.0, 0.25, 0.5, 0.75, 1.0)
    raws = [low + (high - low) * f for f in fractions]
    if curve.direction == "decreasing":
        raws.reverse()
    return list(zip(LEVELS, raws))


def _example_table(curve: Curve, cfg: EngineConfig) -> list[str]:
    if curve.kind == "categorical":
        lines = ["| Category | Score |", "|---|---|"]
        lines += [f"| {category} | {_fmt(score)} |" for category, score in sorted(curve.categories, key=lambda c: c[1])]
        return lines
    if curve.body_mass_mode in ("relative", "mixed"):
        exponent = 1.0 if curve.body_mass_mode == "relative" else cfg.mixed_exponent
        header = "| Level | Normalized value | Score | " + " | ".join(f"Raw at {int(m)} kg" for m in EXAMPLE_BODY_MASSES) + " |"
        lines = [header, "|---|---|---|" + "---|" * len(EXAMPLE_BODY_MASSES)]
        for level, value in _levels(curve):
            raws = " | ".join(_fmt(value * mass**exponent) for mass in EXAMPLE_BODY_MASSES)
            lines.append(f"| {level} | {_fmt(value)} | {_fmt(curve.score(value))} | {raws} |")
        return lines
    lines = ["| Level | Raw value | Score |", "|---|---|---|"]
    lines += [f"| {level} | {_fmt(raw)} | {_fmt(curve.score(raw))} |" for level, raw in _levels(curve)]
    return lines


def render(cfg: EngineConfig) -> str:
    out: list[str] = []
    out.append(f"# ASCEND calibration audit — engine {cfg.engine_version}")
    out.append("")
    out.append("> Generated by `python -m ascend_engine audit` from "
               f"`engine/ascend_engine/config/v{cfg.engine_version.replace('.', '_')}.toml` "
               f"(config hash `{cfg.config_hash[:12]}…`). Do not edit by hand.")
    out.append("")
    out.append(f"**calibration_status: {cfg.calibration_status}.** These are internal ASCEND calibration curves. "
               "They are not scientific norms, percentiles, population rankings or medical thresholds.")
    out.append("")
    out.append("## How scores are formed")
    out.append("")
    out.append("1. Each test's raw result becomes a feature (e.g. speed in m/min).")
    out.append("2. Loaded strength features are adjusted for body size where the curve says so "
               f"(`mixed`: ÷ body mass^{_fmt(cfg.mixed_exponent)}, `relative`: ÷ body mass). Raw values stay in the evidence.")
    out.append("3. A curve maps the feature to 0–100 by piecewise-linear interpolation; the end scores are held outside the range.")
    out.append("4. Sources → subdomain → attribute are weighted means over what was measured, then pulled toward the "
               "missing-evidence prior for anything measurable that is missing (never zero, never higher).")
    out.append("")
    out.append("## Key settings")
    out.append("")
    out.append("| Setting | Value |")
    out.append("|---|---|")
    out.append(f"| Verified threshold | {_fmt(cfg.verified_threshold)} |")
    out.append(f"| Initial calibration cap (before verification) | {_fmt(cfg.initial_calibration_cap)} |")
    out.append(f"| Independent observation separation | {_fmt(cfg.independent_observation_min_hours)} h |")
    out.append(f"| Qualifying verification sources | {', '.join(cfg.qualifying_sources)} |")
    out.append(f"| Missing-evidence prior (provisional, v0.1 only — ADR-036) | {', '.join(f'{a} {_fmt(v)}' for a, v in cfg.missing_prior.items())} |")
    out.append(f"| Confidence weights | {', '.join(f'{k} {_fmt(v)}' for k, v in cfg.confidence_weights.items())} |")
    out.append(f"| Quality factors | {', '.join(f'{k} {_fmt(v)}' for k, v in cfg.quality.items())} |")
    out.append("")
    out.append(f"## Curves ({len(cfg.curves)})")
    for curve_id, curve in cfg.curves.items():
        raw = cfg.raw["curves"][curve_id]
        out.append("")
        out.append(f"### {curve_id}")
        out.append("")
        out.append(f"- **Test:** {curve.test}")
        out.append(f"- **Raw feature:** `{curve.feature}`")
        out.append(f"- **Body normalization:** {curve.body_mass_mode}")
        if curve.kind == "numeric":
            points = ", ".join(f"({_fmt(x)} → {_fmt(y)})" for x, y in curve.points)
            out.append(f"- **Curve points ({curve.direction}):** {points}")
        else:
            out.append("- **Curve:** categorical")
        for line in _usage(curve_id, cfg):
            out.append(f"- **Used by:** {line}")
        out.append(f"- **Rationale:** {raw['rationale']}")
        out.append(f"- **Known weakness:** {raw['weakness']}")
        out.append("")
        out.extend(_example_table(curve, cfg))
    out.append("")
    out.append("## Subdomains without a v0.1 test")
    out.append("")
    for attribute in ATTRIBUTES:
        for sd in cfg.attributes[attribute]:
            if not sd.sources:
                out.append(f"- {attribute} → {sd.name} (weight {_fmt(sd.weight)}): lowers Confidence; does not lower Current.")
    out.append("")
    return "\n".join(out)


def main() -> None:
    print(render(load_config()), end="")
