/**
 * Artwork registry (Design System V2 §9). Components ask for art by semantic
 * id, never by file path, so final pixel art can replace a placeholder by
 * swapping the file (same id, same aspect) without touching components.
 *
 * `status: "placeholder"` marks the procedural stand-ins generated by
 * scripts/generate-art.mjs. `mood` picks the gradient shown while the image
 * loads or if it is missing.
 */

export type ArtMood = "dusk" | "origin" | "forest" | "boss" | "night";

export interface ArtAsset {
  src: string;
  /** Native pixel size; the browser scales it with `image-rendering: pixelated`. */
  width: number;
  height: number;
  mood: ArtMood;
  /** object-position when the slot crops the image. */
  focus: string;
  status: "placeholder" | "final";
}

export const ART = {
  "world.dusk-ruins": { src: "/art/world/dusk-ruins.png", width: 192, height: 96, mood: "dusk", focus: "60% 60%", status: "placeholder" },
  "world.spawn-origin": { src: "/art/world/spawn-origin.png", width: 192, height: 96, mood: "origin", focus: "50% 55%", status: "placeholder" },
  "paths.ascend-map": { src: "/art/paths/ascend-map.png", width: 195, height: 440, mood: "forest", focus: "50% 50%", status: "placeholder" },
  "bosses.guardian-dormant": { src: "/art/bosses/guardian-dormant.png", width: 195, height: 220, mood: "boss", focus: "50% 35%", status: "placeholder" },
  "quests.training-grounds": { src: "/art/quests/training-grounds.png", width: 72, height: 48, mood: "night", focus: "50% 50%", status: "placeholder" },
  "quests.campfire": { src: "/art/quests/campfire.png", width: 72, height: 48, mood: "night", focus: "50% 50%", status: "placeholder" },
  "quests.shrine": { src: "/art/quests/shrine.png", width: 72, height: 48, mood: "night", focus: "50% 50%", status: "placeholder" },
  "quests.road": { src: "/art/quests/road.png", width: 72, height: 48, mood: "dusk", focus: "50% 50%", status: "placeholder" },
  "quests.arena": { src: "/art/quests/arena.png", width: 72, height: 48, mood: "boss", focus: "50% 50%", status: "placeholder" },
  "states.sealed-gate": { src: "/art/states/sealed-gate.png", width: 96, height: 48, mood: "night", focus: "50% 50%", status: "placeholder" },
  "states.quiet-camp": { src: "/art/states/quiet-camp.png", width: 96, height: 48, mood: "night", focus: "50% 50%", status: "placeholder" },
} as const satisfies Record<string, ArtAsset>;

export type ArtId = keyof typeof ART;
